name: Deploy docs.airbyte.com [DUMMY workflow]

on:
  ## XXX uncomment the following when this code gets in good shape
  #push:
  #  branches:
  #    - master
  #  paths:
  #    - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dummy-job:
    name: Deploy Docs Assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Node.js is needed for Yarn
      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          cache: 'yarn'
          cache-dependency-path: docusaurus

      #- name: Setup local Git client
      #  run: |
      #    git remote set-url origin git@github.com:airbytehq/airbyte.git
      #    #git config --global user.email "octavia-squidington-iii@users.noreply.github.com"
      #    #git config --global user.name "octavia-squidington-iii"

      #- name: Install ssh key
      #  uses: shimataro/ssh-key-action@v2.3.1
      #  with:
      #    key: ${{ secrets.DOCS_PRIVATE_SSH_KEY }}
      #    known_hosts: unnecessary

      - name: Run Docusaurus
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./tools/bin/deploy_docusaurus
